version: '3'
services:
  minio:
    image: minio/minio
    command: server /data
    container_name: minio
    environment:
      MINIO_ACCESS_KEY: infra
      MINIO_SECRET_KEY: infrapass
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./data:/data